import * as ReactXPy from "../runtime/runtime.js";

function CodeBlock(props){
  code = props.code ; language = props.language ; ;
  return React.createElement("div", { className: "code-wrapper" },
  React.createElement("div", { className: "code-header" },
    React.createElement("span", { className: "code-lang" },
      language),
    React.createElement("div", { className: "code-dots" },
      React.createElement("span", { className: "dot mac-red" }),
      React.createElement("span", { className: "dot mac-yellow" }),
      React.createElement("span", { className: "dot mac-green" }))),
  React.createElement("pre", { className: "code-pre" },
    React.createElement("code", null,
      code)));
}

function SidebarItem(props){
  id = props.id ; title = props.title ; activeId = props.activeId ; setActiveId = props.setActiveId ; isActive = Object.is (id ,activeId ); className = isActive ? "sidebar-link active" : "sidebar-link" ; ;
  return React.createElement("a", { className: className, href: "#" + id, onClick: (e) => setActiveId(id) },
  title);
}

function Header(props){
  return React.createElement("header", { className: "top-header" },
  React.createElement("div", { className: "header-logo" },
    React.createElement("span", { className: "logo-icon" },
      "⚡"),
    React.createElement("span", { className: "logo-text" },
      "ReactXPy Syntax")),
  React.createElement("div", { className: "header-links" },
    React.createElement("a", { className: "icon-link", href: "https://github.com" },
      "🐙 GitHub"),
    React.createElement("a", { className: "btn-primary", href: "#" },
      "v2.0.0 Docs")));
}

function DocsApp(props){
  const [activeId, setActiveId] = ReactXPy.useState("components" );; DOCS_DATA = { "c1" : "def Button(label):\n    button_name = label + \" Click Me!\"\n    return <button class=\"btn-primary\">\n        <span>{button_name}</span>\n    </button>" ,"c2" : "def Counter():\n    count, setCount = useState(0)\n    useEffect(lambda: document.title = \"Count: \" + count, [count])\n    return <div class=\"counter-box\">\n        <b>Hits: {count}</b>\n        <button onClick={lambda: setCount(count + 1)}>Increment</button>\n    </div>" ,"c3a" : "# CORRECT\n<button onClick={lambda: console.log(\"clicked\")}>" ,"c3b" : "# Passes the 'event' (e) parameter downstream\n<input onChange={lambda e: console.log(e.target.value)} />" ,"c3c" : "def LoginScreen():\n    username, setUsername = useState('')\n\n    def handleSubmit():\n        if (username == 'admin'):\n            alert('Welcome!')\n        else:\n            alert('Denied.')\n\n    # Reference the internal function pointer\n    return <button onClick={handleSubmit}>Login</button>" ,"c4a" : "{ isLoggedIn ? <h1>Welcome!</h1> : <h1>Sign In</h1> }" ,"c4b" : "{ hasErrors && <div class=\"error-modal\">Failed</div> }" ,"c5" : "# Before Compilation (ReactXPy)\ndef FeatureFlag():\n    isEnabled = True\n    sessionObj = None\n\n# After Compilation (dist/bundle.js)\n# function FeatureFlag() {\n#    let isEnabled = true;\n#    let sessionObj = null;\n# }" ,"c6" : "# You write this:\n<div class=\"card\">\n\n# The framework natively mounts this to the React DOM tree:\n# React.createElement('div', { className: 'card' })" ,"c8" : "def Tracker():\n    # count is locked into the closure of the Tracker function scope natively\n    count, setCount = useState(0)\n\n    def logAndIncrement():\n        console.log('Current Hits: ', count)\n        setCount(count + 1)\n\n    return <button onClick={logAndIncrement}>Click</button>" ,"c9" : "{ todos.map(lambda t: React.createElement(\"div\", {className: \"item\"}, t.text)) }" ,"c10" : "# Automatically loads `/src/components/CounterApp.pysx` during AST Linker Build\nimport CounterApp\n\ndef App():\n    return <main>\n       <CounterApp />\n    </main>" } ;
  return React.createElement("div", { className: "docs-layout" },
  React.createElement(Header, null),
  React.createElement("div", { className: "docs-container" },
    React.createElement("aside", { className: "sidebar" },
      React.createElement("div", { className: "sidebar-nav" },
        React.createElement("h4", { className: "nav-title" },
          "Syntax Guide"),
        React.createElement(SidebarItem, { activeId: activeId, id: "architecture", setActiveId: setActiveId, title: "0. How It Works (Architecture)" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "components", setActiveId: setActiveId, title: "1. Defining Components" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "hooks", setActiveId: setActiveId, title: "2. Using React Hooks" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "lambdas", setActiveId: setActiveId, title: "3. Arrow Functions" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "jsx", setActiveId: setActiveId, title: "4. Evaluated JSX" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "primitives", setActiveId: setActiveId, title: "5. Primitive Transpilation" }),
        React.createElement(SidebarItem, { activeId: activeId, id: "arrays", setActiveId: setActiveId, title: "6. Array Mapping" }))),
    React.createElement("main", { className: "main-content" },
      React.createElement("div", { className: "hero-section" },
        React.createElement("h1", null,
          "ReactXPy Syntax Guide"),
        React.createElement("p", { className: "hero-subtitle" },
          "Interactive frontend applications using native Python."),
        React.createElement("p", null,
          "ReactXPy is a revolutionary syntax paradigm that allows developers to write interactive frontend web applications using native Python ",
          React.createElement("code", null,
            ".py"),
          "syntax coupled intricately with HTML (JSX). It bypasses Node.js entirely and utilizes a lightning-fast native C++ transpiler to convert Python code directly into ES6 JavaScript mapped to React DOM components."),
        React.createElement("div", { className: "hero-features" },
          React.createElement("div", { className: "feature-item" },
            React.createElement("span", null,
              "🚀"),
            "Zero Node.js Dependencies"),
          React.createElement("div", { className: "feature-item" },
            React.createElement("span", null,
              "⚛️"),
            "Compile Python directly to React DOM"),
          React.createElement("div", { className: "feature-item" },
            React.createElement("span", null,
              "⚡"),
            "Blazing fast native C++ execution"),
          React.createElement("div", { className: "feature-item" },
            React.createElement("span", null,
              "🔄"),
            "Hot-reloading built-in via dev.py"))),
      React.createElement("div", { className: "sections-wrapper" },
        React.createElement("section", { className: "doc-section", id: "architecture" },
          React.createElement("h2", { className: "section-title" },
            "0. How It Works (Architecture)"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "The compiler is built natively in C++ using the following pipeline:"),
            React.createElement("div", { className: "architecture-steps" },
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "1. reactxpy_compiler (The C++ Core)"),
                React.createElement("p", null,
                  "When a user runs ",
                  React.createElement("code", null,
                    "create-reactxpy-app"),
                  ", a native C++ executable runs locally. It avoids the slow Python runtime entirely.")),
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "2. Lexical Engine"),
                React.createElement("p", null,
                  "Scans the ",
                  React.createElement("code", null,
                    ".pysx"),
                  "files. It detects when you type ",
                  React.createElement("code", null),
                  "(Python scope) and when you type ",
                  React.createElement("code", null,
                    "&lt;div"),
                  "(JSX scope), safely switching modes.")),
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "3. AST Parser"),
                React.createElement("p", null,
                  "Converts the raw tokens into a secure Abstract Syntax Tree (ProgramNode -> FunctionNode -> JSXNode).")),
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "4. Code Generator"),
                React.createElement("p", null,
                  "Traverses the AST. It natively translates Python keywords (",
                  React.createElement("code", null,
                    "True"),
                  "-> ",
                  React.createElement("code", null,
                    "true"),
                  ", ",
                  React.createElement("code", null,
                    "None"),
                  "-> ",
                  React.createElement("code", null,
                    "null"),
                  ") and injects the ",
                  React.createElement("code", null,
                    "ReactXPy.useState"),
                  "bindings dynamically to safely bridge memory.")),
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "5. Linker"),
                React.createElement("p", null,
                  "Flattens all dependencies and imports and concatenates them into a single, cohesive ES6 ",
                  React.createElement("code", null,
                    "bundle.js"),
                  "without requiring Webpack.")),
              React.createElement("div", { className: "arch-step" },
                React.createElement("h4", null,
                  "6. Live Reloader"),
                React.createElement("p", null,
                  "A pure-Python multi-threaded watcher server (",
                  React.createElement("code", null,
                    "dev.py"),
                  ") that watches file modification times (",
                  React.createElement("code", null,
                    "st_mtime"),
                  ") and triggers instant browser hot-reloads over ",
                  React.createElement("code", null,
                    "localhost:3000"),
                  "."))))),
        React.createElement("section", { className: "doc-section", id: "components" },
          React.createElement("h2", { className: "section-title" },
            "1. Defining Components (Pythonic Functions)"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "Components are identical to Python ",
              React.createElement("code", null),
              "functions, but they return raw HTML nodes."),
            React.createElement(CodeBlock, { code: DOCS_DATA["c1"], language: "python" }))),
        React.createElement("section", { className: "doc-section", id: "hooks" },
          React.createElement("h2", { className: "section-title" },
            "2. Deep React Hooks Support"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "State destructuring perfectly mimics Python tuple unpacking."),
            React.createElement(CodeBlock, { code: DOCS_DATA["c2"], language: "python" }))),
        React.createElement("section", { className: "doc-section", id: "lambdas" },
          React.createElement("h2", { className: "section-title" },
            "3. Lambda Event Handlers (No Arrow Functions!)"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "Because JavaScript arrow functions violate standard Python parsers, ReactXPy uses inline Python Lambdas that get natively transpiled to JS arrows on the backend."),
            React.createElement(CodeBlock, { code: DOCS_DATA["c3a"], language: "python" }))),
        React.createElement("section", { className: "doc-section", id: "jsx" },
          React.createElement("h2", { className: "section-title" },
            "4. Logical JSX Expressions inside &#123;&#125;"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "The curly braces escape back to logical evaluation. ReactXPy supports native ternary mapping and && short circuiting."),
            React.createElement(CodeBlock, { code: DOCS_DATA["c4a"], language: "python" }),
            React.createElement(CodeBlock, { code: DOCS_DATA["c4b"], language: "python" }))),
        React.createElement("section", { className: "doc-section", id: "primitives" },
          React.createElement("h2", { className: "section-title" },
            "5. Seamless Primitive Conversions & CSS Classes"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "You do NOT need to learn ",
              React.createElement("code", null,
                "className"),
              ". You can type ",
              React.createElement("code", null,
                "class=\"card\""),
              "exactly like standard HTML, and the C++ engine maps it dynamically."),
            React.createElement("p", null,
              "Python primitives ",
              React.createElement("code", null,
                "True"),
              ", ",
              React.createElement("code", null,
                "False"),
              ", and ",
              React.createElement("code", null,
                "None"),
              "safely compile downward to ",
              React.createElement("code", null,
                "true"),
              ", ",
              React.createElement("code", null,
                "false"),
              ", and ",
              React.createElement("code", null,
                "null"),
              "automatically."))),
        React.createElement("section", { className: "doc-section", id: "arrays" },
          React.createElement("h2", { className: "section-title" },
            "6. Array Mapping Logic"),
          React.createElement("div", { className: "section-content" },
            React.createElement("p", null,
              "Because of the strict single-pass lexer layout, mapping arrays natively inside JSX requires inline ",
              React.createElement("code", null,
                "React.createElement"),
              "bindings for deep nests."),
            React.createElement(CodeBlock, { code: DOCS_DATA["c9"], language: "python" })))))));
}

